### ISSUE TITLE
Mailbox plugin: Insight server crashing when a client attempts to connect using incorrect parameters

### ISSUE THREAD

**Issue by isocolsky** [bitpay/insight-api#182]
When trying to subscribe sending a non-string param as public key the server crashes with the following message:

````
Error: Illegal Argument.
    at Object.validatorFunctions.checkArgument (~/dev/insight/node_modules/insight-bitcore-api/node_modules/preconditions/src/validatorFunctions.js:191:15)
    at messageKey (~/dev/insight/node_modules/insight-bitcore-api/lib/MessageDb.js:56:17)
    at MessageDb.getMessages (~/dev/insight/node_modules/insight-bitcore-api/lib/MessageDb.js:100:10)
    at Socket.<anonymous> (~/dev/insight/node_modules/insight-bitcore-api/plugins/mailbox.js:24:11)
    at Socket.emit (events.js:95:17)
    at Socket.onevent (~/dev/insight/node_modules/insight-bitcore-api/node_modules/socket.io/lib/socket.js:326:8)
    at Socket.onpacket (~/dev/insight/node_modules/insight-bitcore-api/node_modules/socket.io/lib/socket.js:286:12)
    at Client.ondecoded (~/dev/insight/node_modules/insight-bitcore-api/node_modules/socket.io/lib/client.js:181:14)
    at Decoder.Emitter.emit (~/dev/insight/node_modules/insight-bitcore-api/node_modules/socket.io/node_modules/socket.io-parser/node_modules/emitter/index.js:132:20)
    at Decoder.add (~/dev/insight/node_modules/insight-bitcore-api/node_modules/socket.io/node_modules/socket.io-parser/index.js:233:12)
```

**Comment by braydonf** [comment]
No longer relevant with the latest.
