### ISSUE TITLE
Unable to sync - error: NEED_SYNC Ignoring block with non existing prev

### ISSUE THREAD

**Issue by jemekite** [bitpay/insight-api#200]
Hello,

Could you help me, I'm unable to get insight-api to work with qubitcoin, this is error log I've got:
```
info: insight server listening on port 3000 in development mode
info: Seeking file to:0000049ce6324e2f3f17eec90ce7e1f0bc9bcb44f85d769621d83cbb223ddc03
	FOUND Starting Block!
info: Got 0 blocks in current DB, out of 751942 block at bitcoind
info: bitcoind dataDir configured...importing blocks from .dat files
info: First file index: 0
info: Starting from:  0000049ce6324e2f3f17eec90ce7e1f0bc9bcb44f85d769621d83cbb223ddc03
info: status: [0%]
Reading Blockfile /home/abidkecil/.QubitCoin/blocks/blk00000.dat [127 MB]
error: NEED_SYNC Ignoring block with non existing prev:73148056ef3601d7597e3be1a9d9baabbb95b4b32bb661d1edc0fbc4f3267937
[historic_sync] ABORTED with error: NEED_SYNC Ignoring block with non existing prev:73148056ef3601d7597e3be1a9d9baabbb95b4b32bb661d1edc0fbc4f3267937
{ '0': 'connecting to 127.0.0.1:7788' }
{ '0': 'connected to 127.0.0.1:7788' }
info: Previous TIP is now orphan. Back to:undefined

/home/abidkecil/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118
      throw new Error('unable to get info for block:'+ hash);
            ^
Error: unable to get info for block:9bfdf375866f5e8efe20d6249d00c8b6b64d9648e30307ed37a2c083febf626e
    at /home/abidkecil/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118:13
    at /home/abidkecil/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:279:30
    at /home/abidkecil/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/home/abidkecil/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```
This error also happened with other quark based coin, I've tried with deepcoin and getting same error. :(

**Comment by braydonf** [comment]
Outdated
