### ISSUE TITLE
TypeError: Undefined is not a function

### ISSUE THREAD

**Issue by AkiraTakizawa** [bitpay/insight-api#313]
Hello Bitbay

I created a fork yesterday from insight, insight-api and bitcore to support an altcoin. I made some changes in config.js, networks.js and the package.json files first to allow it download from my own repo.

When I run npm install, everything goes as expected, until I try to launch it:
```/home/akira/Source/insight/node_modules/insight-bitcore-api/lib/Rpc.js:11
var  bitcoreRpc  = imports.bitcoreRpc || new RpcClient(config.bitcoind);
                                         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/akira/Source/insight/node_modules/insight-bitcore-api/lib/Rpc.js:11:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/akira/Source/insight/node_modules/insight-bitcore-api/lib/TransactionDb.js:31:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```
The file /home/akira/Source/insight/node_modules/insight-bitcore-api/lib/Rpc.js has no function RpcClient() but Rpc(). When I change that line to 
```
var  bitcoreRpc  = imports.bitcoreRpc || new Rpc(config.bitcoind);
```
, the error disappears, but another error is shown:

```module.js:340
    throw err;
          ^
Error: Cannot find module 'bitcore/util/EncodedData'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:384:19)
    at Function.load (/home/akira/Source/insight/node_modules/insight-bitcore-api/node_modules/soop/soop.js:60:19)
    at Object.<anonymous> (/home/akira/Source/insight/node_modules/insight-bitcore-api/lib/TransactionDb.js:50:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```
I understand that EncodedData is part of Base58-native? It got build and installed according to the log: http://pastebin.com/RhrE45jL

I never experienced this it with the version a few months ago. 
Also, in networks.js I remember I had add the reversed merkle root and hash from the genesis block, together with nonce, timestamp, bits,... This is no longer required?

To be sure I didn't mess up with those small changes I made, the same happens when I clone insight from your repo and want to run it against my bitcoin-core node, which is up to date and configured correctly for use with insight.

**Comment by AkiraTakizawa** [comment]
Problem solved: downgraded to a different version.

**Comment by AnanthKongu** [comment]
Hi,
       I'm new to this, now i'm trying to setup litecoin full node with insight api, I finished litecoin node setup, but no luck with insight api, please some one help me on this, Thanks in advance.
