### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight-api#419]
Hi, when I run "bitcore-node start", I am getting this message:

TypeError: Cannot read property 'split' of undefined
    at AddressController.checkAddrs (/root/mynode/node_modules/insight-api/lib/addresses.js:89:33)
    at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
    at /root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:330:12)
    at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:271:10)
    at /root/mynode/node_modules/insight-api/lib/index.js:56:5
    at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)

I get the same message if I call "/insight-api/addrs/txs" using CURL. 
I uninstall bitcore-node and reinstall it, but nothing. 

Please @braydonf help me, using GET methods, my apps run very slow. Thanks!

PS: I have full sync blockchain. I am running on Ubuntu 14.04.

**Comment by zekylaf** [comment]
I had not noticed it was the same error. Now I delete the # 419
