### ISSUE TITLE
Error in /insight-api/addrs/txs

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight-api#421]
Hi, when I use:

<?php

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"http://<insight-server>:<insight-port>/insight-api/addrs/txs");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "addrs=1DkxXKEDJAjYVLS1WMoyEuS5svJGhMAJ78,1DkxXKEDJAjYVLS1WMoyEuS5svJGhMAJ78");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$remote_server_output = curl_exec ($ch);
 curl_close ($ch);
print_r($remote_server_output);

?>

I get this message: 

TypeError: Cannot read property 'split' of undefined
   at AddressController.checkAddrs (/root/mynode/node_modules/insight-api/lib/addresses.js:89:33)
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:131:13)
   at /root/mynode/node_modules/insight-api/lib/index.js:63:5
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at /root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:330:12)

Can anybody help please?

**Comment by braydonf** [comment]
Duplicate? https://github.com/bitpay/insight-api/issues/421

**Comment by zekylaf** [comment]
I had not noticed it was the same error. Now I delete the # 419

Do you know what is happening with this error?

**Comment by braydonf** [comment]
Looks like there was a bug with parsing x-www-form-urlencoded data and is fixed with: https://github.com/bitpay/insight-api/pull/422

**Comment by zekylaf** [comment]
Hi, I use these comands:

"cd mynode"
"bitcore-node uninstall insight-api"
"cd .."
"npm uninstall -g bitcore-node"

then...

"npm install -g bitcore-node@latest"
"cd mynode"
"bitcore-node install insight-api"

And when I do this in php:

<?php

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"http://:/insight-api/addrs/txs");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "addrs=1DkxXKEDJAjYVLS1WMoyEuS5svJGhMAJ78,1DkxXKEDJAjYVLS1WMoyEuS5svJGhMAJ78");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$remote_server_output = curl_exec ($ch);
curl_close ($ch);
print_r($remote_server_output);

?>



I get the same message: 

TypeError: Cannot read property 'split' of undefined
   at AddressController.checkAddrs (/root/mynode/node_modules/insight-api/lib/addresses.js:89:33)
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:131:13)
   at /root/mynode/node_modules/insight-api/lib/index.js:63:5
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at next (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)
   at /root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/root/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:330:12) 



Am i doing something wrong?

**Comment by braydonf** [comment]
The [patch to fix it](https://github.com/bitpay/insight-api/pull/422) has not yet been merged.

**Comment by zekylaf** [comment]
Ok, thanks :+1:

**Comment by saroar** [comment]
i dont get where is solution please give me more information thanks
