### ISSUE TITLE
Error installing insight-api with bitcore-node

### ISSUE THREAD

**Issue by joncursi** [bitpay/insight-api#468]
I have created a new bitcore node, and per the instructions in the Wiki, am trying to install insight-api. Any idea why I am receiving the following error?

```
$ bitcore-node install insight-api
insight-api@0.3.2 node_modules/insight-api
├── bitcore-message@1.0.2
├── body-parser@1.15.0 (bytes@2.2.0, content-type@1.0.1, depd@1.1.0, on-finished@2.3.0, http-errors@1.4.0, raw-body@2.1.6, qs@6.1.0, debug@2.2.0, type-is@1.6.12, iconv-lite@0.4.13)
├── lodash@2.4.2
├── request@2.69.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@6.0.2, tough-cookie@2.2.2, mime-types@2.1.10, aws4@1.3.2, form-data@1.0.0-rc4, bl@1.0.3, http-signature@1.1.1, har-validator@2.0.6, hawk@3.1.3)
└── async@2.0.0-rc.1 (lodash@4.6.1)

/Users/jcursi/Sites/joncursi/bitcore/node_modules/bitcore-lib/lib/util/preconditions.js:9
      throw new errors.InvalidState(message);
            ^
Invalid state: undefined
Error
    at Error.NodeError (/Users/jcursi/Sites/joncursi/bitcore/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.module.exports.checkState (/Users/jcursi/Sites/joncursi/bitcore/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)
    at /Users/jcursi/Sites/joncursi/bitcore/node_modules/bitcore-node/lib/scaffold/add.js:106:11
    at ChildProcess.<anonymous> (/Users/jcursi/Sites/joncursi/bitcore/node_modules/bitcore-node/lib/scaffold/add.js:57:14)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by braydonf** [comment]
Have you tried with this guide: https://bitcore.io/guides/full-node it goes through installing `bitcore` that packages all required pieces together.

**Comment by joncursi** [comment]
I have, and I have a node up and running but getting the error above. Everything is working as intended, but I figured I'd raise the thrown installation error here.

**Comment by braydonf** [comment]
Looks like it's already installed and why it's asserting. A better error message could be useful here.
