### ISSUE TITLE
Crash: RangeError: Buffer length (0) must be a multiple of size (0)

### ISSUE THREAD

**Issue by wtogami** [bitpay/insight-api#50]
```
[historic_sync] status: [99.679%]
GET /api/block/00000000000000002a7ad54a6640b5a7041909409e3aea92203360fbc63919ee 200 37ms - 633b
[p2p_sync] Handle tx: f42144956d927b2e76755304717065f1d0682f7fd37e3d50173ab21a86780584
[p2p_sync] Handle tx: a08a32d08f6bfd2e4cf37dddf686d1f298323cb9a34885099cb5a9302a57f5d8
[p2p_sync] Handle tx: e44fd66ac7f8601a4bc18c06bc54b13db44dcc00517bb1745cb55ddd8efb116b
[p2p_sync] Handle tx: 34efa80ddcb84714a81543647bc51bc7227d149789439c705ee93abbff47f1f5
[p2p_sync] Handle tx: 4e1a95ece38e55d1987fbf554073d04a28c4514496029be16f9251eeec67188d
[p2p_sync] Handle tx: db1208daf70d06881a892bcfb58203b1705ec34dd0aeb0a62f7832ac8ebbb52d
[p2p_sync] Handle tx: c849f6dde59e2c826622193da9baa5f03c54929e6ec05693f29ba17ec05f92a9
[p2p_sync] Handle tx: 1db2e4d6d472e7e0ce44bbb637b5160d219ea0554ea46b689278d6bf2e606ac7
[p2p_sync] Handle tx: 6f814b0b3bdfab0f3ae292881d8062fa594548c7654be3114bcea093bbd971af
[p2p_sync] Handle tx: 5da11adcfa4ea9b3d60503e70893c73edb53bae536dc20131fc331540a666dfc
[p2p_sync] Handle tx: da432f996b3e03ed151c90bdfd033b45f56afb72f7c4529e654632e6d51800f2
[p2p_sync] Handle tx: b4a8c83225d6bf12b74dba77701d3e6f273dabec01883f47380307c0ec8e96fc
GET /api/block/00000000000000002a7ad54a6640b5a7041909409e3aea92203360fbc63919ee 200 29ms - 633b
[p2p_sync] Handle tx: 85a553f742a7c93ca41e6246f96258404cc6f8d9412815a069167af56fbc2cdf

/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bignum/index.js:329
        throw new RangeError('Buffer length (' + buf.length + ')'
              ^
RangeError: Buffer length (0) must be a multiple of size (0)
    at Function.BigNum.fromBuffer (/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bignum/index.js:329:15)
    at exports.valueToBigInt (/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/util/util.js:101:19)
    at Object.exports.formatValue (/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/util/util.js:235:15)
    at /home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/Transaction.js:587:19
    at Array.map (native)
    at Transaction.getStandardizedObject (/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/Transaction.js:583:24)
    at /home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/Block.js:577:15
    at Array.map (native)
    at Block.getStandardizedObject (/home/btc/insight/node_modules/insight-bitcore-api/node_modules/bitcore/Block.js:576:15)
    at /home/btc/insight/node_modules/insight-bitcore-api/lib/HistoricSync.js:138:19
    at /home/btc/insight/node_modules/insight-bitcore-api/lib/BlockExtractor.js:150:12
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by braydonf** [comment]
No longer relevant with v0.3.0
