### ISSUE TITLE
[Security] Full Path Disclosure

### ISSUE THREAD

**Issue by shayanb** [bitpay/insight-api#542]
Sending unexpected* data to broadcast endpoint `/insight-api/tx/send` results in an error message which contains path of the node app.

[Full Path Disclosure Vulnerability](https://www.owasp.org/index.php/Full_Path_Disclosure)

Example Code:
```JS
function broadcastTX (transactionHex, done) {
  var broadcastUrl = url + 'tx/send';
  request.post({
    headers: {'content-type': 'application/json'},
    url: broadcastUrl,
    params: {'rawtx': transactionHex}
  }, function (error, response, body) {
    if (error) console.log(error);
    console.log('txid', body);
    done(body);
  });
}
```
---
examples:

1. Trezor.io (https://bch-bitcore2.trezor.io)
`/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/bitcoind-rpc/lib/index.js`
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;toString&#39; of undefined<br> &nbsp; &nbsp;at Array.types.str (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/bitcoind-rpc/lib/index.js:283:17)<br> &nbsp; &nbsp;at RpcClient.&lt;anonymous&gt; (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/bitcoind-rpc/lib/index.js:259:35)<br> &nbsp; &nbsp;at Bitcoin.sendTransaction (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:1806:15)<br> &nbsp; &nbsp;at Node.self.(anonymous function) [as sendTransaction] (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/bitcore-node/lib/node.js:223:27)<br> &nbsp; &nbsp;at TxController.send (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/insight-api/lib/transactions.js:303:13)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /mnt/data/ssd/satoshilabs/bitcore-bcc/bitcore/node_modules/express/lib/router/index.js:281:22</pre>
</body>
</html>
```

2. blockdozer.com
`/home/bitprim/mynode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js`
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;toString&#39; of undefined<br> &nbsp; &nbsp;at Array.types.str (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:260:17)<br> &nbsp; &nbsp;at RpcClient.&lt;anonymous&gt; (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:236:35)<br> &nbsp; &nbsp;at Bitcoin.sendTransaction (/home/bitprim/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:1804:15)<br> &nbsp; &nbsp;at Node.self.(anonymous function) [as sendTransaction] (/home/bitprim/mynode/node_modules/bitcore-node/lib/node.js:223:27)<br> &nbsp; &nbsp;at TxController.send (/home/bitprim/mynode/node_modules/insight-api/lib/transactions.js:303:13)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/bitprim/mynode/node_modules/bitcore-node/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /home/bitprim/mynode/node_modules/bitcore-node/node_modules/express/lib/router/index.js:281:22</pre>
</body>
</html>
```

It seems that all other deployment of insight has this vulnerability.

**Comment by gabegattis** [comment]
This is probably due to a non `production` environment, which causes express to send a stacktrace.

**Comment by gabegattis** [comment]
We should have a way to set the `NODE_ENV` environment variable to "production".

**Comment by shayanb** [comment]
It is applicable to almost all insight-api's available online atm.

**Comment by NicoleG25** [comment]
Do you plan to address this vulnerability ? 

> We should have a way to set the `NODE_ENV` environment variable to "production".
