### ISSUE TITLE
insight-api 404 - Resource not load

### ISSUE THREAD

**Issue by NeoKings** [bitpay/insight-api#543]
I have an error on connect insight. 
This is the message:  Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at : and failed.)

Some JS console errors:

`<img src="http://neokings.com/insight-log.jpg">`

My bitcore-node.json config file:

{
  "network": "livenet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api",
    "insight-ui",
    "web"
  ],
  "servicesConfig": {
    "insight-api": {
      "routePrefix": "api",
      "disableRateLimiter": true,
      "enableCache": true
    },
    "bitcoind": {
        "spawn": {
        "datadir": "/home/ubuntu/.bitcoin",
        "exec": "/home/ubuntu/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/bitcore-node/bin/bitcoind"
}
}
}
}

**Comment by saroar** [comment]
same here 

```[InsightApi] testnet request: http://127.0.0.1:3001/insight-api/addrs/utxo post {:addrs=>"2N61wnRBfrBEPHQq8jRe9Z8dMJcUwoSrtq5"}
Completed 401 Unauthorized in 38ms (ActiveRecord: 3.9ms)


  
RestClient::BadRequest (400 Bad Request):
  
app/services/insight_api.rb:37:in `call'
app/services/insight_api.rb:23:in `fetch_utxos'```

**Comment by giancarlopetrini** [comment]
Also experiencing this issue.
